# Generated by Django 4.2.7 on 2023-12-15 19:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_clinic_doctors_alter_issuer_clinic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='issuer',
        ),
        migrations.AddField(
            model_name='issuer',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
