# Generated by Django 4.2.7 on 2023-12-01 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='issuer',
        ),
        migrations.AddField(
            model_name='customuser',
            name='issuer',
            field=models.ManyToManyField(blank=True, related_name='users', to='users.issuer'),
        ),
    ]
