# Generated by Django 4.2.7 on 2023-12-05 18:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
        ('users', '0003_remove_customuser_issuer_customuser_issuer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issuer',
            name='clinic',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='web.clinic'),
        ),
        migrations.AlterField(
            model_name='issuer',
            name='doctor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='web.doctor'),
        ),
    ]
