# Generated by Django 4.2.7 on 2023-12-15 20:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_customuser_issuer_issuer_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='issuer',
            name='user',
        ),
        migrations.AddField(
            model_name='clinic',
            name='doctors',
            field=models.ManyToManyField(related_name='clinics', through='users.Issuer', to='users.doctor'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='issuer',
            field=models.ManyToManyField(blank=True, related_name='users', to='users.issuer'),
        ),
        migrations.AlterField(
            model_name='issuer',
            name='clinic',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='users.clinic'),
        ),
    ]
