# Generated by Django 4.2.7 on 2023-12-05 18:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
        ('users', '0004_alter_issuer_clinic_alter_issuer_doctor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('council_number', models.CharField(max_length=100)),
                ('sus_number', models.CharField(max_length=100)),
                ('speciality', models.CharField(max_length=100)),
                ('patients', models.ManyToManyField(related_name='doctors', through='web.PatientCareLink', to='web.patient')),
            ],
        ),
        migrations.CreateModel(
            name='Clinic',
            fields=[
                ('name', models.CharField(max_length=100)),
                ('sus_number', models.CharField(max_length=7, primary_key=True, serialize=False)),
                ('address', models.CharField(max_length=100)),
                ('address_number', models.CharField(max_length=6)),
                ('city', models.CharField(max_length=100)),
                ('neighborhood', models.CharField(max_length=100)),
                ('zip_code', models.CharField(max_length=9)),
                ('phone', models.CharField(max_length=100)),
                ('doctors', models.ManyToManyField(related_name='clinics', through='users.Issuer', to='users.doctor')),
                ('patients', models.ManyToManyField(related_name='clinics', through='web.PatientCareLink', to='web.patient')),
            ],
        ),
        migrations.AlterField(
            model_name='issuer',
            name='clinic',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='users.clinic'),
        ),
        migrations.AlterField(
            model_name='issuer',
            name='doctor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='users.doctor'),
        ),
    ]
