# Generated by Django 4.2.7 on 2023-12-10 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_doctor_clinic_alter_issuer_clinic_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='clinic',
            field=models.ManyToManyField(blank=True, related_name='users', to='users.clinic'),
        ),
    ]
