# Generated by Django 4.2.7 on 2023-12-16 10:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prescription',
            name='visit',
        ),
        migrations.AddField(
            model_name='patient',
            name='visit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='web.visit'),
        ),
        migrations.AddField(
            model_name='visit',
            name='prescription',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='web.prescription'),
        ),
        migrations.AlterField(
            model_name='visit',
            name='link',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='web.patientcarelink'),
        ),
    ]
