# Generated by Django 4.2.7 on 2023-12-05 18:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_doctor_clinic_alter_issuer_clinic_and_more'),
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='patients',
        ),
        migrations.AlterField(
            model_name='patientcarelink',
            name='clinic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='users.clinic'),
        ),
        migrations.AlterField(
            model_name='patientcarelink',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='users.doctor'),
        ),
        migrations.DeleteModel(
            name='Clinic',
        ),
        migrations.DeleteModel(
            name='Doctor',
        ),
    ]
