# Generated by Django 4.2.7 on 2023-12-17 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_issuer_user_clinic_doctors_customuser_issuer_and_more'),
        ('web', '0005_remove_visit_link_visit_issuer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='issuer',
            field=models.ManyToManyField(related_name='patients', to='users.issuer'),
        ),
    ]
