# Generated by Django 4.2.7 on 2024-01-06 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0007_alter_prescription_posology'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescription',
            name='conditional_data',
            field=models.JSONField(null=True),
        ),
    ]
